on:
  push:
  issues:
    types:
      - opened
      - edited

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      id: hello
      uses: GBKS/github-events-calendar@v1.1